#docker-compose -f .\eclipse-workspace\Redis\docker-compose-mongo.yaml up -d
#docker-compose -f .\eclipse-workspace\Redis\docker-compose-mongo.yaml down
version: "3.8"

volumes:
  mongo_data:

services:
  mongo:
    image: mongo:5.0
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    #restart: no
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=test.123
      - ME_CONFIG_MONGODB_URL=mongodb://root:test.123@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8081:8081"
      
